### PR TITLE
feat(indexer): update indexer to use historical proxy instead of erc20-relay

### PR DESCRIPTION
**Pull request by playX18**
@mertwole 
@osipov-mit

### CODE REVIEW

**Review by mertwole — APPROVED** [review]
Can be merged when you wish as new versions of contracts are already deployed

**Comment by playX18** [comment]
> Can be merged when you wish as new versions of contracts are already deployed

Lets wait for green CI just in case and then merge

**Comment by mertwole** [comment]
> Lets wait for green CI just in case and then merge

I'd wait for @osipov-mit review if you haven't done in #196 yet

**Comment by playX18** [comment]
> > Lets wait for green CI just in case and then merge
> 
> I'd wait for @osipov-mit review if you haven't done in #196 yet

Alright, then lets wait.

**Review by osipov-mit — APPROVED** [review]
All good, but pls don't merge it as I have to do some things on the server before the deployment. 
I'll merge when it's ready

**Pull request merged**
